# Generated by Django 2.0.2 on 2018-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_trafficlightinformationtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLightDetectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.CharField(default='', max_length=25)),
                ('device', models.CharField(default='', max_length=25)),
                ('traffic_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('realiable_value', models.IntegerField(blank=True, default=None, null=True)),
                ('congestion_count', models.IntegerField(blank=True, default=None, null=True)),
                ('queue_length', models.IntegerField(blank=True, default=None, null=True)),
                ('vehicle_count', models.IntegerField(blank=True, default=None, null=True)),
                ('wait_time_max', models.FloatField(blank=True, default=None, null=True)),
                ('wait_time_avg', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('street_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
