# Generated by Django 2.0.2 on 2018-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_trafficlightdetectors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficLightInformationTest',
        ),
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='intresection',
            field=models.CharField(default='', max_length=25),
        ),
    ]
