# Generated by Django 2.0.2 on 2018-04-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20180418_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlightdetectors',
            old_name='intresection',
            new_name='intersection',
        ),
    ]
