# Generated by Django 2.0.2 on 2018-04-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20180418_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlightdetectors',
            old_name='latitude',
            new_name='e_coordinate',
        ),
        migrations.RenameField(
            model_name='trafficlightdetectors',
            old_name='longitude',
            new_name='n_coordinate',
        ),
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='x_coo',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='y_coo',
            field=models.CharField(default='', max_length=25),
        ),
    ]
