# Generated by Django 2.0.2 on 2018-04-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20180419_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='x_coo',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='y_coo',
            field=models.CharField(default='', max_length=25),
        ),
    ]
