# Generated by Django 2.0.2 on 2018-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20180419_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='status',
            field=models.CharField(default='', max_length=5),
        ),
    ]
